### ISSUE TITLE
Strict Validation

### ISSUE THREAD

**Issue by Asbjoedt** [mikeebowen/ooxml-validator-vscode#14]
For context see the discussion
https://github.com/mikeebowen/ooxml-validator-vscode/discussions/13

Latest reply from @mikeebowen
> Hi @Asbjoedt, that PR was merged in the SDK, so we are able to determine strict vs transitional. Most of the changes will actually be in the [OOXML Validator](https://github.com/mikeebowen/OOXML-Validator). This isn't a validation error, so I will have to extend the validator and get the information manually and add it in. I will work to get this in when I can. Please create a feature request on the [issues page](https://github.com/mikeebowen/ooxml-validator-vscode/issues) to help track this. Thanks!

Our situation
We have a big interest in seeing this feature implemented. Reach out if you need help other than coding.

**Comment by mikeebowen** [comment]
@Asbjoedt How do you think this should be displayed? It's not an error so I don't think it should be in the error list. Should we have a line above where it says something like "This document is saved in transitional mode"?

**Comment by Asbjoedt** [comment]
Agreed, it is not an error. Yes, add a line. May I suggest to phrase it:

"This document is saved in OOXML Transitional format"
and
"This document is saved in OOXML Strict format"

**Comment by mikeebowen** [comment]
I think we should do something like:

"The document is saved in OOXML Strict format"
and
"The document is not saved in OOXML Strict format"

because the property is actually `StrictRelationshipFound` so we can only tell if it is strict or something else, not whether it is strict, transitional, or something else.

**Comment by Asbjoedt** [comment]
I understand. It is fair to presume, that the document is transtional, if not strict. Also, the standard allows for not having any markup of Strict or Transitional and then by default the document will be Transitional. So we have no real way of knowing whether anything is Transitional. We only have real way of knowing something is Strict, because the markup will be mandatory.

I am referring to following sections of the OOXML standard:

Page 195, about Word
Specifies the conformance class (§2.1) to which the WordprocessingML document
conforms.
If this attribute is omitted, its default value is transitional.
[Example: Consider the following WordprocessingML Main Document part markup:
<w:document w:conformance="strict">
 …
</w:document>
This document has a conformance attribute value of strict, therefore it conforms to
the WML Strict conformance class. end example]
The possible values for this attribute are defined by the ST_ConformanceClass simple
type (§22.9.2.2).

Page 1575, about spreadsheet
Specifies the conformance class (§2.1) to which the SpreadsheetML document conforms.
If this attribute is omitted, its default value is transitional.
[Example: Consider the following SpreadsheetML Workbook part markup:
<workbook conformance="strict">
 …
</workbook>
This document has a conformance attribute value of strict, therefore it conforms to
the SML Strict conformance class. end example]
The possible values for this attribute are defined by the ST_ConformanceClass simple
type (§22.9.2.2).

Page 2542, about presentations
Specifies the conformance class (§2.1) to which the PresentationML document conforms.
If this attribute is omitted, its default value is transitional.
[Example: Consider the following PresentationML Presentation part markup:
<p:presentation conformance="strict">
 …
</p:presentation>
This document has a conformance attribute value of strict, therefore it conforms to
the PML Strict conformance class. end example]
The possible values for this attribute are defined by the ST_ConformanceClass simple
type (§22.9.2.2).

Regarding DrawingML, there's different strings in the schema

Page 4002 (I am unsure if this one is about Strict/Transitional Conformance)
<xsd:complexType name="CT_GraphicalObjectData">
843 <xsd:sequence>
844 <xsd:any minOccurs="0" maxOccurs="unbounded" processContents="strict"/>
845 </xsd:sequence>
846 <xsd:attribute name="uri" type="xsd:token" use="required"/>
847 </xsd:complexType>


Page 4129
<xsd:simpleType name="ST_ConformanceClass">
89 <xsd:restriction base="xsd:string">
90 <xsd:enumeration value="strict"/>
91 <xsd:enumeration value="transitional"/>
92 </xsd:restriction>
93 </xsd:simpleType>

Page 4402
3 s_ST_ConformanceClass = string "strict" | string "transitional"

About document conformance in general in the standard
Page 1:
2.1 Document Conformance
A document of conformance class Office Open XML Strict shall be a package of conformance class OPC, as
specified in ISO/IEC 29500-2, for which all the following shall hold:
 The document obeys all constraints specified in this Part of ISO/IEC 29500
 The document is of category Wordprocessing, Spreadsheet, or Presentation, as defined in §4
 For each OPC Part of the document of the types listed in §11.3, §12.3, §13.3, §14.2 or §15.2, all the
following shall hold:
i. The Part may contain markup in the Markup Compatibility namespace as specified in
ISO/IEC 29500-3
ii. After the removal of any extensions by an MCE processor as specified in ISO/IEC 29500-3,
the part is valid against the strict W3C XML Schema (Appendix A)
This Part of ISO/IEC 29500 uses the following further terms to refer to documents of conformance class Office
Open XML Strict:
 WML Strict, if the document is of category Wordprocessing
 SML Strict, if the document is of category Spreadsheet
 PML Strict, if the document is of category Presentation

**Comment by Asbjoedt** [comment]
Based on the above examination of the standard, I am leaning to defining our Strict validation as "conformance".

Therefore we may call it, if you agree

"The document is conformant with OOXML Strict format"
and
"The document is not conformant with OOXML Strict format"

Secondly, I don't know if you can use the above examination to doing Strict validation on the string values rather than the Open XML SDK relationship property, or is this in fact what this property provides us?

**Comment by Asbjoedt** [comment]
@mikeebowen great.
I relayed my question to the people who worked on the StrictRelationshipFound at the Open XML SDK repository, to be sure my organisation fully understands the mechanics behind the property.

**Comment by mikeebowen** [comment]
I tried to find an issue you created on the [Open XML SDK issues page](https://github.com/OfficeDev/Open-XML-SDK/issues), to check and make sure the team knows the context, but I couldn't find one. Can you post the link?

**Comment by Asbjoedt** [comment]
Of course, here you go
https://github.com/OfficeDev/Open-XML-SDK/pull/716

**Comment by mikeebowen** [comment]
Hi @Asbjoedt ,

I'm closing this issue, because this [Release of the OOXML-Validator CLI](https://github.com/mikeebowen/OOXML-Validator/releases) adds the ability to return xml with an `IsStrict` attribute that is true for documents in strict mode and false otherwise. If you want this to be possible in VS Code extension, open another issue and I'll take another swing at making that work.

**Comment by Asbjoedt** [comment]
@mikeebowen 
Thanks man.
