### ISSUE TITLE
Error Validating Word 2007 File

### ISSUE THREAD

**Issue by dstringvc** [mikeebowen/ooxml-validator-vscode#20]
Trying to validate a docx file. Changing the File Format Version appears to work for all values except 2007. When I try to use 2007, I get a pop-up error "Unexpected token U in JSON at position 0". Validation passes for all other versions.

![Screenshot 2022-11-29 102528](https://user-images.githubusercontent.com/13070995/204599495-e97285df-f10a-4f78-88ab-af455036e6dc.png)

**Comment by dstringvc** [comment]
Here is the most recent file where I got that error. Thanks for looking at it.

[thunder-file_11a69750.docx](https://github.com/mikeebowen/ooxml-validator-vscode/files/10117638/thunder-file_11a69750.docx)

**Comment by mikeebowen** [comment]
Thanks @dstringvc . Can you tell me how this file was created? Was it made with Word or an SDK like the [OpenXML SDK](https://github.com/OfficeDev/Open-XML-SDK)} or with something else?

**Comment by dstringvc** [comment]
I generated that file using the [NPOI](https://github.com/nissl-lab/npoi) library.

**Comment by mikeebowen** [comment]
Does it open correctly in newer versions of Word?

**Comment by dstringvc** [comment]
Based on anecdotal reports from the IT directory, it opens correctly using the Office365 (subscription) desktop version (The only desktop version I have access to is 2007). When opening the document with the Office365 Online version of Word, in "editing" mode, the small table at the top of the document is broken (all data is shown in a single column). However, when I switch to "viewing" mode, the document appears correctly.

**Comment by dstringvc** [comment]
Here's something odd. I created a new document from scratch using Word 2007 desktop. It contains nothing fancy, just a few paragraphs with simple text. When I tried to validate it, I got the same error as show in my original post. The file is attached.
[bacon_ipsum.docx](https://github.com/mikeebowen/ooxml-validator-vscode/files/10118405/bacon_ipsum.docx)

**Comment by mikeebowen** [comment]
Thanks for the file. I am able to reproduce it as well. I'll try to debug this and see what is going on this week.

**Comment by mikeebowen** [comment]
I found the bug causing this and created a release to fix it. Update the extension to version [1.5.2](https://github.com/mikeebowen/ooxml-validator-vscode/releases/tag/v1.5.2) to fix the issue. 

Thanks for finding this!
