### ISSUE TITLE
Troubleshooting running 

### ISSUE THREAD

**Issue by jeroen-binnekamp** [mikeebowen/ooxml-validator-vscode#23]
Hello Mike,

Looking forward using your Extension to validate some excel files. However I do not seem to get it to work. 

Maybe you can point me in the right direction. 

I am working on a Mac and am running Visual Studio Code 1.80.0.

I have installed the latest dotnet. dotnet --info tells me:
 Microsoft.NETCore.App 7.0.0 [/usr/local/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App]

This is then also the path I put in settings.json:

"ooxml.dotNetPath": "/usr/local/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App",

When I try running the extension, I get the following error:

"undefined" is not a valid JSON

thanks for you response!

Regards,
Jeroen

**Comment by mikeebowen** [comment]
Hi @jeroen-binnekamp,

If you do not set `ooxml.dotNetPath`, do you get the same error?

**Comment by jeroen-binnekamp** [comment]
Hi @mikeebowen ,
After removing the setting ooxml.dotNetPath I get the following error:

<img width="491" alt="image" src="https://github.com/mikeebowen/ooxml-validator-vscode/assets/57395669/4b013164-e102-43ea-990f-22a374ebe56c">

**Comment by mikeebowen** [comment]
Have you installed the [.NET Install Tool for Extension Authors](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscode-dotnet-runtime)? It's necessary to run without `ooxml.dotNetPath`. 

I will also investigate this, but I can't reproduce it on Windows, so I need to find a Mac to test on first.

**Comment by DaveMcCrady** [comment]
I get the exact same issue.   Same steps to reproduce. Resolved using the following setting.
On an M1 the path to dotnet framework is /usr/local/share/dotnet/dotnet

**Comment by carlgleisner** [comment]
> /usr/local/share/dotnet/dotnet

This solved the same issue for me 🙏🏼
