### ISSUE TITLE
Can you add a configuration that specifies the dotnet path

### ISSUE THREAD

**Issue by cnscottluo** [mikeebowen/ooxml-validator-vscode#7]
every validate，downloading dotnet... very slowly, then failded.

**Comment by mikeebowen** [comment]
Hi @cnscottluo , this should be possible. I am out of town for Thanksgiving, but I'll look into it next week. If you have time to code it up and send a pull request, that would be awesome too!

**Comment by mikeebowen** [comment]
@cnscottluo release [v1.1.0](https://github.com/mikeebowen/ooxml-validator-vscode/releases/tag/v1.1.0) adds `ooxml.dotNetPath` to the configuration, which, if set, uses that for the .Net Runtime instead of downloading it every time. Let me know if that resolves your issues with downloading .Net.

**Comment by cnscottluo** [comment]
> @cnscottluo release [v1.1.0](https://github.com/mikeebowen/ooxml-validator-vscode/releases/tag/v1.1.0) adds `ooxml.dotNetPath` to the configuration, which, if set, uses that for the .Net Runtime instead of downloading it every time. Let me know if that resolves your issues with downloading .Net.

thanks, the version v1.1.0 work for me
