### ISSUE TITLE
Allow validation of OOXML macro-enabled and add-in files

### ISSUE THREAD

**Issue by rajch** [mikeebowen/ooxml-validator-vscode#8]
Hi

Could you allow the validator to process files with the following extensions:

* .docm, .dotm, .dotx (Word macro-enabled document, macro-enabled template, macroless template)
* .xlsm, .xltm, .xltx, .xlam (Same for excel, plus add-in)
* .pptm,  .potm, .potx, .ppam, .ppsm, .ppsx (Same for PowerPoint, plus macro-enabled and macroless show files)

These are all OOXML files, so the validator should work just fine on them.

**Comment by mikeebowen** [comment]
Hi @rajch , Thanks for the request! This should be a quick change. I will get it in this week or next.
